version: "3.9"

services:
  bot:
    build: .
    container_name: bot_app
    command: python dev_runner.py
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5678:5678"
    depends_on:
      - redis
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A bot.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
