version: "3.9"

services:
  bot:
    build: .
    container_name: bot_app
    # command: python dev_runner.py
    command: python -m debugpy --listen 0.0.0.0:5678 dev_runner.py

    volumes:
      - .:/app
      - ./local.db:/app/local.db
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0          # Celery Redis
      - REDIS_BOT_URL=redis://redis_bot:6379/0  # 👈 окремий для бот-черги
    ports:
      - "5678:5678"
    depends_on:
      - redis
      - redis_bot
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: celery_worker
    command: python celery_dev_runner.py
    volumes:
      - .:/app
      - ./local.db:/app/local.db
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/0
      - REDIS_BOT_URL=redis://redis_bot:6379/0
    ports:
      - "5679:5679"
    depends_on:
      - redis
      - redis_bot
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A bot.celery_app.celery_app beat --loglevel=info
    volumes:
      - .:/app
      - ./local.db:/app/local.db
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - REDIS_BOT_URL=redis://redis_bot:6379/0
    depends_on:
      - redis
      - redis_bot
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  redis_bot:
    image: redis:7-alpine
    container_name: redis_bot
    restart: unless-stopped
