"""add telegram_id and is_verify to carrier_company

Revision ID: 1094ecaf433c
Revises: 
Create Date: 2025-08-03 22:28:46.985793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1094ecaf433c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrier_companies')
    op.drop_index(op.f('ix_shipment_request_client_telegram_id'), table_name='shipment_request')
    op.drop_table('shipment_request')
    op.drop_index(op.f('ix_carriers_telegram_id'), table_name='carriers')
    op.drop_table('carriers')
    op.drop_index(op.f('ix_support_sessions_user_id'), table_name='support_sessions')
    op.drop_table('support_sessions')
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('support_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('from_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['support_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=1)
    op.create_table('support_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_sessions_user_id'), 'support_sessions', ['user_id'], unique=False)
    op.create_table('carriers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('from_city', sa.VARCHAR(), nullable=False),
    sa.Column('to_city', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carriers_telegram_id'), 'carriers', ['telegram_id'], unique=1)
    op.create_table('shipment_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('from_city', sa.VARCHAR(), nullable=False),
    sa.Column('to_city', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('date_text', sa.VARCHAR(), nullable=False),
    sa.Column('cargo_type', sa.VARCHAR(), nullable=False),
    sa.Column('volume', sa.VARCHAR(), nullable=False),
    sa.Column('weight', sa.VARCHAR(), nullable=False),
    sa.Column('loading', sa.VARCHAR(), nullable=False),
    sa.Column('unloading', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_request_client_telegram_id'), 'shipment_request', ['client_telegram_id'], unique=1)
    op.create_table('carrier_companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ownership_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tax_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('office_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
