"""Create new table SheetBinding

Revision ID: 5df3dd4a6d3a
Revises: f8137d14514f
Create Date: 2025-08-18 21:36:54.569256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df3dd4a6d3a'
down_revision: Union[str, Sequence[str], None] = 'f8137d14514f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sheet_bindings_owner_telegram_id'), table_name='sheet_bindings')
    op.drop_table('sheet_bindings')
    op.drop_table('transport_vehicles')
    op.drop_index(op.f('ix_carrier_companies_telegram_id'), table_name='carrier_companies')
    op.drop_table('carrier_companies')
    op.drop_index(op.f('ix_support_sessions_user_id'), table_name='support_sessions')
    op.drop_table('support_sessions')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_shipment_request_client_telegram_id'), table_name='shipment_request')
    op.drop_table('shipment_request')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('is_verify', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('google_sheet_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('google_sheet_id', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=1)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_table('shipment_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_telegram_id', sa.INTEGER(), nullable=False),
    sa.Column('from_city', sa.VARCHAR(), nullable=False),
    sa.Column('to_city', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('date_text', sa.VARCHAR(), nullable=False),
    sa.Column('cargo_type', sa.VARCHAR(), nullable=False),
    sa.Column('volume', sa.VARCHAR(), nullable=False),
    sa.Column('weight', sa.VARCHAR(), nullable=False),
    sa.Column('loading', sa.VARCHAR(), nullable=False),
    sa.Column('unloading', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_request_client_telegram_id'), 'shipment_request', ['client_telegram_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('from_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['support_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_sessions_user_id'), 'support_sessions', ['user_id'], unique=False)
    op.create_table('carrier_companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('is_verify', sa.BOOLEAN(), nullable=False),
    sa.Column('contact_full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('google_sheet_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('google_sheet_id', sa.VARCHAR(length=512), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tax_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('office_address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_companies_telegram_id'), 'carrier_companies', ['telegram_id'], unique=1)
    op.create_table('transport_vehicles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=100), nullable=False),
    sa.Column('load_capacity_tons', sa.VARCHAR(length=20), nullable=False),
    sa.Column('body_volume_m3', sa.VARCHAR(length=20), nullable=True),
    sa.Column('special_equipment', sa.TEXT(), nullable=True),
    sa.Column('driver_fullname', sa.VARCHAR(length=100), nullable=True),
    sa.Column('driver_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('carrier_company_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_company_id'], ['carrier_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet_bindings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=8), nullable=False),
    sa.Column('sheet_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sheet_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('last_opened_at', sa.DATETIME(), nullable=True),
    sa.Column('last_opened_revision', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_opened_by_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_opened_by_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_opened_modified_time', sa.DATETIME(), nullable=True),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.Column('last_synced_revision', sa.VARCHAR(length=64), nullable=True),
    sa.Column('sync_in_progress', sa.BOOLEAN(), nullable=False),
    sa.Column('cooldown_until', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_telegram_id'], ['clients.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_telegram_id', 'kind', name=op.f('uq_binding_owner_kind'))
    )
    op.create_index(op.f('ix_sheet_bindings_owner_telegram_id'), 'sheet_bindings', ['owner_telegram_id'], unique=False)
    # ### end Alembic commands ###
