"""Change cargo descr to None

Revision ID: 8b49bd661df4
Revises: 
Create Date: 2025-09-03 22:24:25.745592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b49bd661df4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_vehicles')
    op.drop_index(op.f('ix_google_sheet_bindings_telegram_id'), table_name='google_sheet_bindings')
    op.drop_table('google_sheet_bindings')
    op.drop_table('sheet_bindings')
    op.drop_index(op.f('ix_shipment_requests_client_telegram_id'), table_name='shipment_requests')
    op.drop_table('shipment_requests')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_carrier_companies_email'), table_name='carrier_companies')
    op.drop_index(op.f('ix_carrier_companies_phone'), table_name='carrier_companies')
    op.drop_index(op.f('ix_carrier_companies_telegram_id'), table_name='carrier_companies')
    op.drop_table('carrier_companies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tax_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_index(op.f('ix_carrier_companies_telegram_id'), 'carrier_companies', ['telegram_id'], unique=1)
    op.create_index(op.f('ix_carrier_companies_phone'), 'carrier_companies', ['phone'], unique=False)
    op.create_index(op.f('ix_carrier_companies_email'), 'carrier_companies', ['email'], unique=1)
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=1)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=1)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=1)
    op.create_table('shipment_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('from_city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('to_city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('date_text', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cargo_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cargo_description', sa.TEXT(), nullable=True),
    sa.Column('weight', sa.VARCHAR(length=20), nullable=False),
    sa.Column('volume', sa.VARCHAR(length=20), nullable=True),
    sa.Column('loading', sa.VARCHAR(length=100), nullable=False),
    sa.Column('unloading', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['client_telegram_id'], ['clients.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_requests_client_telegram_id'), 'shipment_requests', ['client_telegram_id'], unique=False)
    op.create_table('sheet_bindings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=8), nullable=False),
    sa.Column('sheet_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sheet_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('last_revision_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_modified_time', sa.DATETIME(), nullable=True),
    sa.Column('last_modified_by_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_modified_by_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.Column('last_synced_revision', sa.VARCHAR(length=64), nullable=True),
    sa.Column('sync_in_progress', sa.BOOLEAN(), nullable=False),
    sa.Column('cooldown_until', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'owner_type', 'kind', name=op.f('uq_binding_owner_kind'))
    )
    op.create_table('google_sheet_bindings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('owner_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('sheet_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('sheet_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('sheet_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('last_revision_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_modified_time', sa.DATETIME(), nullable=True),
    sa.Column('last_modified_by_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.Column('last_synced_revision', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id', 'owner_type', 'sheet_type', name=op.f('uq_binding_owner_sheet_type'))
    )
    op.create_index(op.f('ix_google_sheet_bindings_telegram_id'), 'google_sheet_bindings', ['telegram_id'], unique=False)
    op.create_table('transport_vehicles',
    sa.Column('carrier_company_id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('load_capacity_tons', sa.FLOAT(), nullable=False),
    sa.Column('body_volume_m3', sa.FLOAT(), nullable=True),
    sa.Column('loading_equipment', sa.TEXT(), nullable=True),
    sa.Column('driver_fullname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('driver_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_company_id'], ['carrier_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###
