"""Add to Client model field -google_sheet_id

Revision ID: a03e823d8d46
Revises: 13ab80ee337b
Create Date: 2025-08-18 16:28:07.615111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03e823d8d46'
down_revision: Union[str, Sequence[str], None] = '13ab80ee337b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
